### ISSUE TITLE
Has this project already failed?

### ISSUE THREAD

**Issue by zhuolingzhao007** [layoutBox/StackViewLayout#10]
It hasn't been updated for two years and hasn't been merged into master.

**Comment by lucdion** [comment]
Hi, true, the project is 95% percent completed, but I didn't had the time to complete it in recent years, mostly because where I work we now mostly use SwiftUI and Autolayout  🤷‍♂️

**Comment by zhuolingzhao007** [comment]
Thank you for your contributions to open source, wish you all the best in your work
